### ISSUE TITLE
Tracking & TO-DO

### ISSUE THREAD

**Issue by notsatvrn** [notsatvrn/Interstellar#1]
The grand tracking & TO-DO list for Interstellar.

# TO-DO

# Tracking
This section is dedicated to tracking patch versions and their sources.

"abandoned" sources shouldn't be checked, as they are clearly never receiving another update.

Hopefully this will make keeping things up-to-date much easier, and help track progress.

### Custom Patches
- [x] Use FastRandom
- [x] Improve loot table refresh logic
  - based on Akarin's "Don't trigger Lootable Refresh for non player interaction"
- [x] Improve hand swing logic
  - based on Lithium's entity.fast_hand_swing

### Fork Patches
- [ ] Linear region format (LinearPaper) **(4d2377f)**
- [ ] Patina **(2f27cee)**
  - [x] skip event if no listeners
  - [x] hardcode version
  - [x] don't create new random instance (expanded)
- [x] KTP **(62fb014)**
  - [x] Optimize spigot event bus
- [ ] Gale **(276e903)**
  - [x] Dev import deobfuscation fixes 
  - [ ] Include hardware specs in timings
  - [x] Faster floating-point positive modulo
  - [x] Optimize matching item checks
  - [ ] Instantly continue on world upgrade finish
- [ ] Kaiiju **(abandoned)**
  - [x] Use Math.floor instead of fastfloor
- [ ] EmpireCraft **(120465e)**
- [ ] Akarin **(eba57d2)**
  - [x] Save Json list asynchronously
  - [x] Swaps the predicate order of collision
  - [x] Avoid double I/O operation on load player file
- [ ] Sugarcane **(abandoned)**
  - [x] Stop wasting resources on JsonList#get
  - [ ] Last tick time API + NSPT command
  - [ ] Disable mob spawners below TPS threshold
  - [ ] NBT cache
- [x] P4per **(abandoned)**
  - [x] Performance improvements (split into 3 patches)
- [ ] JettPack **(abandoned)**
  - [ ] some entity micro opts
  - [ ] Better handling of async tasks
  - [ ] Use MCUtil.asyncExecutor for MAIN_WORKER_EXECUTOR in Util
- [ ] Slice **(e62b92a)**
  - [ ] Packet obfuscation and reduction
- [ ] Petal **(abandoned)**
  - [ ] async path processing
  - [ ] multithreaded tracking
- [ ] SparklyPaper **(a573948)**
  - [x] Skip "distanceToSqr" call in "ServerEntity#sendChanges" if the delta movement hasn't changed 
  - [x] Skip dirty stats copy when requesting player stats
  - [x] Skip EntityScheduler's executeTick checks if there isn't any tasks to be run
  - [x] Cache coordinate key used for nearby players when ticking chunks
  - [x] Optimize "canSee" checks
  - [x] Optimize tickBlockEntities
  - [x] Track how much MSPT each world used

### Mod Patches
- [ ] Lithium
  - [x] ai.raid
  - [x] alloc.composter (expanded into reduce allocs)
  - [x] cached_hashcode
  - [x] gen
  - [x] math.fast_util
  - [x] math.sine_lut
  - [x] entity.fast_retrieval
- [x] Krypton
  - [x] network.microopt
  - [x] network.pipeline
  - [x] change Netty PooledByteBufAllocator arena size
- [ ] Carpet Fixes
  - [x] Optimized getBiome call
- [ ] C2ME
- [ ] VMP
- [ ] Hydrogen **(abandoned)**
- [ ] FerriteCore

**Comment by notsatvrn** [comment]
this project is kinda in maintenance while i work on [opencraft](https://github.com/notsatvrn/opencraft)
if you want me to update upstream or smth tell me cause im not gonna pay too much attention to this for a while
maybe just use Purpur it's fast enough lmao

**Comment by MrRaposinha** [comment]
@notsatvrn Could you please update this?

**Comment by notsatvrn** [comment]
see updated readme
